### ISSUE TITLE
Consider terms and report back to trustees

### ISSUE THREAD

**Issue by Scarzy** [srobo/committee-tasks#10]
Please report back to trustees by end of month

Are your terms of office appropriate? Does it make sense to take a month off (if your team does so)?

**Comment by PeterJCLaw** [comment]
In my experience the infrastructure team running on a long duration has worked well. We've been able to plan things like budgets decoupled from the competition cycle, which fits well with the need to actually have infrastructure all the time.

As we've somewhat been pushed for capacity during the competition cycle (as our volunteers overlap a lot with the other teams), having space outside the competition cycle to pick things up is quite valuable.

**Comment by sedders123** [comment]
The Marketing Committee feels like it doesn't make sense to take a month off for us. We should be aiming to put out social media, blog posts, and other marketing material all year round, and while there are quieter months we can still be prepping.

**Comment by samjmartin04** [comment]
As James said, Marketing having a break is not really needed. There is certainly an argument (both for Marketing and particularly the competition team) for the change over period to be brought forward a month so that planning for next year's competition cycle can start earlier with the new committee.
